# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brain Food
email: me@brianchang.info
description: > # this means to ignore newlines until "baseurl:"
  Enrich your brain with the musings of Brian Chang.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://brianchang.info" # the base hostname & protocol for your site
twitter_username: eviltoylet
github_username:  eviltoylet

# Build settings
markdown: kramdown
